FROM golang:1.24.2 AS builder
WORKDIR /pvz

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ ./cmd/
COPY internal/ ./internal/
RUN CGO_ENABLED=0 GOOS=linux go build -a -o pvz-app ./cmd/pvz/main.go

FROM alpine:latest
RUN apk add --no-cache dumb-init
WORKDIR /pvz
COPY --from=builder /pvz/pvz-app .
EXPOSE 8080
EXPOSE 3000
EXPOSE 9000
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["./pvz-app"]
